### ISSUE TITLE
Handling package naming conflicts.

### ISSUE THREAD

**Issue by mbostock** [mbostock/crom#2]
With a decentralized registry, packages can have naming conflicts. Even if Crom only uses GitHub, there can be multiple packages with the same name (e.g., forks). A simple name is nice for loading, but not guaranteed unique.

Perhaps related, should Crom allow you to install multiple versions simultaneously?

**Comment by kgryte** [comment]
You should research how Go handles package management. Name conflicts are a non-issue as packages are saved according to their path, which is unique. What Go does __not__ handle, however, is multiple versions. For this, NPM's approach is arguably best.

**Comment by mbostock** [comment]
Now using content-addressable storage, like ied.
