### ISSUE TITLE
URLs should be the canonical identifier.

### ISSUE THREAD

**Issue by mbostock** [mbostock/crom#4]
That’s the only valid option for decentralized packages, right? The entire internet is our registry.

Even if `crom install d3` does some magic to figure out that `d3` means `https://github.com/mbostock/d3`, the *canonical* way for referring to a package should always be its URL. So if we were to have a package.json-equivalent to specify dependencies, it shouldn’t record the package name but instead the complete URL.

Maybe for convenience it allows you to author a package.json with short names, but the next time you use it, it should (perhaps interactively) expand those to URLs.

**Comment by mbostock** [comment]
Related, this should work, and avoid the search:

```
crom install https://github.com/mbostock/d3
```

**Comment by mbostock** [comment]
You may also want to compute and store the cryptographic hash at the same time you install, so you know if it changes.

Maybe the folder name should even be the hash. But then you might want a short name alias for loading packages? `require(url)` would be blech.

**Comment by BurntCaramel** [comment]
Maybe the URL gets stored with an alias?
```
{
  "d3": {
    "url": "https://github.com/mbostock/d3",
    "hash": "xxxxxx"
  }
}
```

**Comment by mbostock** [comment]
Yeah, I think something like that would work well. Probably the metadata would store a list of all installed packages, and then Crom would apply a disambiguation algorithm when loading (e.g., `require`) to map a short name to a specific installed module. And it’d probably throw an error if the name couldn’t be safely disambiguated (e.g., two versions of `d3` installed).

**Comment by mbostock** [comment]
Fixed.
