### ISSUE TITLE
`crom install d3-voronoi@0.2` installs hijacked package

### ISSUE THREAD

**Issue by grahamc** [mbostock/crom#8]
1. create a repository named d3-voronoi (https://github.com/grahamc/d3-voronoi)
2. publish a few releases
3. ask a 26 close friends to star the repository
4. ...??  inject XSS ??
5. PROFIT!

```
$ crom install d3-voronoi
searching d3-voronoi
✓ https://github.com/grahamc/d3-voronoi (★26)
✓ https://github.com/d3/d3-voronoi (★25)
versions *
✓ 0.2.1
assets v0.2.1
✓ d3-voronoi.zip
installed d3-voronoi@0.2.1
↳ crom_modules/d3-voronoi/README.md
```

```
$ cat crom_modules/d3-voronoi/README.md 
Didn't get what you want?

Sorry, too popular.
```

**Comment by mbostock** [comment]
I don’t see that with 0.0.2…

``
$ crom install d3-voronoi
✓ https://github.com/d3/d3-voronoi (★25)
✗ https://github.com/grahamc/d3-voronoi (★29)
✓ https://github.com/d3/d3-voronoi/releases/tag/v0.2.1
↳ https://github.com/d3/d3-voronoi/releases/download/v0.2.1/d3-voronoi.zip
+ crom_modules/1623cb85c3012fddec81a6882e5f45cc779cee43ec9d72e57ce0e0f15fe5fae2.zip
+ crom_modules/1eb846e5b81ea7e25dab3184fa777a8db325d01146cdae02aa589b2349d162b8
- crom_modules/1623cb85c3012fddec81a6882e5f45cc779cee43ec9d72e57ce0e0f15fe5fae2.zip
+ crom.json
```

But that’s most just a coincidence.

Yes, if you rely on a name in a decentralized system, it is necessarily mutable. You can try to apply heuristics to resolve the name as best you can, but it is no guarantee of correctness. Names are inherently local in meaning.

Hence why Crom tells you exactly what you did, which was resolve to resolve the name as https://github.com/grahamc/d3-voronoi. Why is this surprising? If you are installing software blindly, what do you expect? The same thing can happen if I have a typo when installing an npm package or accidentally substitute a different name. You can specify a more explicit name to provide more security at the expense of convenience.

```
crom install d3/d3-voronoi
crom install https://github.com/d3/d3-voronoi
```

Importantly, crom does not persist the name of the package you install. It persists the URL. So I install d3-voronoi as https://github.com/d3/d3-voronoi, and I upgrade it later, I’m not at risk of it coming from a different place.
